[package]
name = "bitcoind-rpc-timeout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpc = "0.13.0"
serde_json = { version = "1.0.83", features = ["raw_value"] }
